gping: lock cargo dependencies
The new version of dns-lookup failed to build with musl:

error[E0308]: mismatched types
   --> gping/src/main.rs:331:19
    |
331 |         Ok(ip) => ip,
    |                   ^^ expected `Vec<IpAddr>`, found opaque type
    |
   ::: /builder/shared-workdir/build/sdk/dl/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/dns-lookup-2.1.0/src/lookup.rs:17:46
    |
17  | pub fn lookup_host(host: &str) -> io::Result<impl Iterator<Item = IpAddr> + use<>> {
    |                                              ------------------------------------ the found opaque type
    |
    = note:   expected struct `Vec<IpAddr>`

Signed-off-by: Tianling Shen <cnsztl@immortalwrt.org>
(cherry picked from commit 0118fb489659088565f948994d7c81d9f41a20a1)